<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>st</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>GNU Smalltalk</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(super|self|thisContext)\b</string>
			<key>name</key>
			<string>keyword.language.smalltalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\:\=|\^)</string>
			<key>name</key>
			<string>keyword.language.smalltalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(nil|true|false)\b</string>
			<key>name</key>
			<string>constant.language.smalltalk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>comment.smalltalk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.smalltalk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>string.quoted.smalltalk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>string.quoted.smalltalk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>string.quoted.smalltalk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>string.quoted.smalltalk</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.smalltalk.gnu</string>
	<key>uuid</key>
	<string>8D5B0A47-F312-4E18-84FB-7186E302726F</string>
</dict>
</plist>
